[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"

[global]
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false
